### ISSUE TITLE
Server Id problems

### ISSUE THREAD

**Issue by thorsanvil** [BrizzleMFD/MechanicalTitan#54]
So atm I am trying to setup a server for me and my friend + girlfriend. The current problem i am having mainly which is preventing me from playing is that, when i try and make anything that is not vanilla minecraft the object is unmakeable. 

Its visually there but when trying to take it out of the crafting table it fails. I am assuming this is due to server setup. but i am not sure 100% sure the exact setup, cause i have not seen any specific instructions. 

My process:
         -Extracted MechanicalTitanServer.zip
         -Run forge-1.7.10-10.13.2.1231-universal.jar
         - agree to eula
         - run minecraft_server.1.7.10.jar (through a .bat file)
Server runs fine and mods are present in the mod list and in NEI
but in creative i try and cheat in an item to test, and it gives me an error saying there is nothing at the id stated.

I read somewhere that you need to move the mods present in the minecraft folder created, but in all honesty i don't know what specific folder and where to place them if need be.

HELP!! Please :)

**Comment by BrizzleMFD** [comment]
Yeah as for moving the folders basically go in to the minecraft folder and move all folders in it up to the same folder that the minecraft folder itself is in then delete the now empty minecraft folder and restart

**Comment by thorsanvil** [comment]
So thanks for the tip it worked perfectly the mods started loading on launch and it was making progress but it seems that this now has happened and idk how to procceed.

---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 1/10/15 12:11 PM
Description: Exception in server tick loop

cpw.mods.fml.common.MissingModsException
	at cpw.mods.fml.common.Loader.sortModList(Loader.java:227)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:472)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
(there is more to the error log but its mainly unloads untill it hits ForgeMultiPart and then it says

Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

)

**Comment by BrizzleMFD** [comment]
have you removed any mods?

**Comment by thorsanvil** [comment]
no, but i now used the minecraft file you provided on github instead of the one provided through the ftb server download.

I delete journey maps and mob discombobulator. and its loading but i keep seeing these failures to load after minefactory reloaded fails. 

After giving the server a bigger perma gen size it loaded through the error (but it was still present). and got through to loading of the map. The server is now running but i haven't tested it but damn it took forever to load.

here is my bat file for loading it (without the qoutes):
 
"java -Xmx20480M -Xms20480M -jar  -XX:PermSize=256M -XX:MaxPermSize=512M  forge-1.7.10-10.13.2.1231-universal.jar"


My one concern atm is what didn't load might be broken or really glitch, here is what it says when it gets to the part im concerned at

[13:20:17] [main/WARN] [FML]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[13:20:17] [main/WARN] [FML]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[13:20:17] [main/WARN] [FML]: The coremod com.dynious.refinedrelocation.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[13:20:17] [main/ERROR] [FML]: Coremod ResonantPluginLoader: Unable to class load the plugin resonant.core.ResonantPluginLoader
java.lang.ClassNotFoundException: resonant.core.ResonantPluginLoader
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_71]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_71]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_71]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.7.0_71]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_71]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_71]
	at java.lang.Class.forName0(Native Method) ~[?:1.7.0_71]
	at java.lang.Class.forName(Unknown Source) ~[?:1.7.0_71]
	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:417) [forge-1.7.10-10.13.2.1231-universal.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:346) [forge-1.7.10-10.13.2.1231-universal.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214) [forge-1.7.10-10.13.2.1231-universal.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.2.1231-universal.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupServer(FMLLaunchHandler.java:74) [forge-1.7.10-10.13.2.1231-universal.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForServerLaunch(FMLLaunchHandler.java:39) [forge-1.7.10-10.13.2.1231-universal.jar:?]
	at cpw.mods.fml.common.launcher.FMLServerTweaker.injectIntoClassLoader(FMLServerTweaker.java:23) [forge-1.7.10-10.13.2.1231-universal.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [forge-1.7.10-10.13.2.1231-universal.jar:?]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [forge-1.7.10-10.13.2.1231-universal.jar:?]
[13:20:17] [main/WARN] [FML]: The coremod thaumcraft.codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[13:20:17] [main/WARN] [FML]: The coremod thaumic.tinkerer.preloader.ThaumicTLoaderContainer does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[13:20:17] [main/WARN] [FML]: The coremod universalelectricity.core.UELoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[13:20:17] [main/ERROR] [FML]: Coremod UELoader: The plugin class universalelectricity.core.UELoader was not instantiable
java.lang.InstantiationException: universalelectricity.core.UELoader
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.7.0_71]
	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:458) [forge-1.7.10-10.13.2.1231-universal.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:346) [forge-1.7.10-10.13.2.1231-universal.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214) [forge-1.7.10-10.13.2.1231-universal.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.2.1231-universal.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupServer(FMLLaunchHandler.java:74) [forge-1.7.10-10.13.2.1231-universal.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForServerLaunch(FMLLaunchHandler.java:39) [forge-1.7.10-10.13.2.1231-universal.jar:?]
	at cpw.mods.fml.common.launcher.FMLServerTweaker.injectIntoClassLoader(FMLServerTweaker.java:23) [forge-1.7.10-10.13.2.1231-universal.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [forge-1.7.10-10.13.2.1231-universal.jar:?]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [forge-1.7.10-10.13.2.1231-universal.jar:?]
[13:20:17] [main/WARN] [FML]: The coremod codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[13:20:17] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:20:17] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[13:20:17] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:20:17] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:20:17] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:20:19] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[13:20:19] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:20:19] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:20:19] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:20:19] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:20:19] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:20:19] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:20:19] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:20:19] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:20:19] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:20:19] [main/INFO] [IC2-core]: Loaded library ejml-0.23.jar.


and



[13:21:41] [Server thread/WARN] [MineFactoryReloaded]: catching
java.lang.NullPointerException
	at cofh.mod.BaseMod.loadLang(BaseMod.java:188) [BaseMod.class:?]
	at powercrystals.minefactoryreloaded.MineFactoryReloadedCore.preInit(MineFactoryReloadedCore.java:277) [MineFactoryReloadedCore.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) [LoadController.class:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118) [LoadController.class:?]
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513) [Loader.class:?]
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88) [FMLServerHandler.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[13:21:41] [Server thread/INFO] [CoFH ASM]: Stripping methods and fields from powercrystals.minefactoryreloaded.tile.transport.TileEntityConveyor
[13:21:41] [Server thread/INFO] [CoFH ASM]: Stripping methods and fields from powercrystals.minefactoryreloaded.tile.rednet.TileEntityRedNetEnergy
[13:21:41] [Server thread/INFO] [CoFH ASM]: Stripping methods and fields from powercrystals.minefactoryreloaded.tile.rednet.TileEntityRedNetHistorian
[13:21:41] [Server thread/INFO] [CoFH ASM]: Adding runtime interfaces to powercrystals.minefactoryreloaded.item.ItemFactoryHammer
[13:21:42] [Server thread/INFO] [PulseManager-TConstruct]: Skipping Pulse Tinkers Mystcraft Compatibility; missing dependency: Mystcraft
[13:21:43] [Server thread/INFO] [Electro-Magic Tools]: Starting planning the world domination

**Comment by thorsanvil** [comment]
over all if these aren't major concerns then it works great :D!, but that means that the server version that ftb has is buggy and might need to be replaced cause i couldn't get it to load for the life of me.

**Comment by BrizzleMFD** [comment]
using the link available on here will mean you wont have any server only mods like Morpheus and such. Also it was good you removed the map that is client only and will crash your server.
